baseURL = 'https://joseph-c100.github.io'
languageCode = 'en-us'
title = 'Joseph C'

pagination.pagerSize = '8' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters


[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Visual Journalist'
	mainSections = 'posts'

[author]
	name = 'Joseph C'
	bio = 'Visual journalist'

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Personal work'
		pageRef = '/personal/'
		weight = 15
	[[menu.main]]
		name = 'Info'
		pageRef = '/about'
		weight = 20
	[[menu.main]]
		name = 'Writing'
		pageRef = '/writing/'
		weight = 25
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 30


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'


[caches]
  [caches.images]
    dir = ':cacheDir/images'